### ISSUE TITLE
Bug when comparing some competitors

### ISSUE THREAD

**Issue by EnzoHideki** [PedroBortolli/CFStats#25]
Ran into error when comparing some competitors, such as scott_wu and tourist.

![screenshot from 2018-06-25 02-54-01](https://user-images.githubusercontent.com/7076941/41832601-1216ce9c-7823-11e8-94a0-af0fcdab5046.png)

**Comment by PedroBortolli** [comment]
The CF Api would return contest ids as nil sometimes, that was leading to a bug when trying to sort them using the sort_by function.

Now it casts the contest id to integer before sorting and also there's an exception for when the value is nil
