### ISSUE TITLE
First user's resize isn't working

### ISSUE THREAD

**Issue by PedroBortolli** [PedroBortolli/CFStats#35]
On /result page, when you zoom in and then zoom out, the first user row doesn't get resized properly

![image](https://user-images.githubusercontent.com/22510346/42291009-47a8b862-7f9f-11e8-8edd-6e8ff92ef434.png)

While the second user is fine

![image](https://user-images.githubusercontent.com/22510346/42291013-51324bd2-7f9f-11e8-9820-e096ceeba5b5.png)

**Comment by EnzoHideki** [comment]
Fixed on 7eb85e
