### ISSUE TITLE
Some stats are cut off screen on mobile comparison

### ISSUE THREAD

**Issue by EnzoHideki** [PedroBortolli/CFStats#51]

**Comment by PedroBortolli** [comment]
Could you please provide an example/screenshot?

**Comment by EnzoHideki** [comment]
![screenshot_2018-07-19-17-45-54](https://user-images.githubusercontent.com/7076941/42969185-c93b2be8-8b7b-11e8-8898-7f6f1df0292b.png)

**Comment by EnzoHideki** [comment]
With 9938cbe, this issue should now be solved.
